### ISSUE TITLE
LGPLv3, Copyright Assignment

### ISSUE THREAD

**Issue by hlieberman** [flutterwireless/FlutterWirelessLibrary#1]
Hi there!

On the [call for developers](http://community.flutterwireless.com/t/flutter-call-for-developers-c-c-edition/126/8), the license is stated to be "LGPL v2.1 or later" and a proprietary license.  Currently, the code has the LGPL v3 in the LICENSE file.  If you intend for it to be licensed under LGPL v2.1, you must change this before any code is accepted from anyone but yourself.

Additionally, if you want to maintain the ability to have a proprietary license, you will have to setup a CONTRIBUTOR file that requires submission of a contributor license agreement.  I recommend, if you want to go down that path, also requiring sign-off on each individual commit as well as the signed CLA on file before you accept the code is important.

Personally, I prefer free software to proprietary software, so I won't help you with the latter. ;-)

**Comment by sequoia-hope** [comment]
Err, wanted to automatically close the issue with the commit, but I see now that I should have included the right text in the commit message. But yes, thanks for the issue, I have resolved it. :)
